apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  rules:
  - host: softfall2019-si.software
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-svc
          servicePort: 8080
      - path: /catering(/|$)(.*)
        backend:
          serviceName: catering-svc
          servicePort: 3030
          
      - path: /event(/|$)(.*)
        backend:
          serviceName: event-svc
          servicePort: 3131
      - path: /facility(/|$)(.*)
        backend:
          serviceName: facility-svc
          servicePort: 3232
